---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ui
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: nginx-k8s.equipement.gov.ma
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-webapp-service
                port:
                  number: 80
